In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/home/momo/Downloads/dataset for prec/cleaned_data/04-before-traansformation.csv")
df.head(3)

,datetime,temp,dew,humidity,sealevelpressure,precipitation,temp_EMA_3_days,humidity_lag_3_days,season_sin,season_cos,winddir_sin,winddir_cos,moisture_flux,temperature_inversion_index
0,2016-07-01,21.1,68.9,96.8,1009.1,53.1,21.1,87.425,-0.587785,-0.809017,0.979575,0.201078,872.370534,-0.0956
1,2016-07-02,21.7,69.0,93.9,1009.8,13.7,21.4,87.425,-0.587785,-0.809017,0.137445,-0.990509,118.735594,-0.0946
2,2016-07-03,23.2,69.8,88.4,1007.7,2.0,22.3,87.425,-0.587785,-0.809017,-0.589196,-0.807990,-666.687462,-0.0932

In [4]:
df.describe()

,temp,dew,humidity,sealevelpressure,precipitation,temp_EMA_3_days,humidity_lag_3_days,season_sin,season_cos,winddir_sin,winddir_cos,moisture_flux,temperature_inversion_index
count,3287.000000,3287.000000,3287.000000,3287.000000,3287.000000,3287.000000,3287.000000,3.287000e+03,3287.000000,3287.000000,3287.000000,3287.000000,3287.000000
mean,18.616946,56.303955,75.341253,1015.409370,3.827520,18.616440,75.339147,-9.556878e-02,0.158047,-0.376695,-0.493701,-308.055542,-0.075374
std,5.062757,11.475371,11.599571,4.393349,10.494321,5.014758,11.596504,6.418477e-01,0.744455,0.599068,0.505632,574.149281,0.014667
min,6.700000,29.000000,25.200000,1001.300000,0.000000,7.597384,25.200000,-9.510565e-01,-0.809017,-0.999998,-1.000000,-6701.285898,-0.100400
25%,14.100000,45.900000,69.500000,1012.100000,0.000000,14.026757,69.500000,-5.877853e-01,-0.809017,-0.884581,-0.911762,-666.151449,-0.089600
50%,19.900000,56.500000,76.600000,1015.700000,0.000000,19.980250,76.600000,-2.449294e-16,0.309017,-0.551937,-0.673013,-436.604641,-0.075000
75%,23.200000,68.200000,83.600000,1018.800000,1.800000,23.194401,83.600000,5.877853e-01,1.000000,-0.061049,-0.187381,-53.205338,-0.064200
max,27.200000,74.300000,100.000000,1025.600000,164.300000,27.055841,100.000000,9.510565e-01,1.000000,0.999986,0.999848,6793.876678,-0.019800

In [6]:
len(df[df["precipitation"] == 0])

2066